# modules/report_generator.py
"""
Report Generation Engine
Creates audit-ready PDF reports for compliance and financial reporting
"""

from typing import Dict, List, Any
from datetime import datetime
import pandas as pd
from io import BytesIO
import json


class ReportGenerator:
    """Generates comprehensive financial and compliance reports"""
    
    def __init__(self, organization_name: str = "CFO Pulse AI",
                 organization_tin: str = "0000000001"):
        self.organization_name = organization_name
        self.organization_tin = organization_tin
        self.report_version = "1.0"
    
    def create_monthly_tax_report(self, transactions_df: pd.DataFrame,
                                  tax_summary: Dict,
                                  month: int,
                                  year: int) -> Dict:
        """
        Create monthly tax filing report.
        
        Args:
            transactions_df: DataFrame with all transactions
            tax_summary: Tax summary dictionary
            month: Month number (1-12)
            year: Year
            
        Returns:
            Dictionary with report data (can be converted to PDF)
        """
        months = ["", "January", "February", "March", "April", "May", "June",
                  "July", "August", "September", "October", "November", "December"]
        month_name = months[month]
        
        report = {
            "document_type": "Monthly Tax Report",
            "organization": self.organization_name,
            "organization_tin": self.organization_tin,
            "period": f"{month_name} {year}",
            "report_date": datetime.now().strftime("%Y-%m-%d"),
            "report_version": self.report_version,
            
            "executive_summary": {
                "total_transactions": tax_summary.get("total_transactions", 0),
                "total_amount": tax_summary.get("total_amount", 0),
                "total_vat": tax_summary.get("total_vat", 0),
                "total_tot": tax_summary.get("total_tot", 0),
                "total_tax_liability": tax_summary.get("total_tax", 0),
                "compliance_status": "Compliant" if tax_summary.get("total_transactions", 0) > 0 else "No Activity"
            },
            
            "tax_breakdown": {
                "vat": {
                    "rate": "15%",
                    "amount": tax_summary.get("total_vat", 0),
                    "percentage_of_total": tax_summary.get("vat_percentage", 0)
                },
                "tot": {
                    "rate": "2-10%",
                    "amount": tax_summary.get("total_tot", 0),
                    "percentage_of_total": tax_summary.get("tot_percentage", 0)
                },
                "total_tax_due": tax_summary.get("total_tax", 0)
            },
            
            "transaction_details": {
                "count": len(transactions_df) if transactions_df is not None else 0,
                "date_range": {
                    "from": f"{year}-{month:02d}-01",
                    "to": f"{year}-{month:02d}-31"
                }
            },
            
            "filing_requirements": {
                "deadline": f"{year}-{month+1 if month < 12 else month}-25",
                "submission_method": "Ministry of Revenue (MOR) Portal",
                "required_documents": [
                    "Transaction summary reports",
                    "VAT schedule",
                    "ToT schedule",
                    "Entity tax identification"
                ]
            },
            
            "notes": "This report is audit-ready and suitable for government filing.",
            "certificate": "Report generated by CFO Pulse AI Compliance Engine"
        }
        
        return report
    
    def create_compliance_report(self, scan_results: Dict,
                                violation_summary: Dict) -> Dict:
        """
        Create compliance audit report.
        
        Args:
            scan_results: Results from compliance engine scan
            violation_summary: Violation summary dictionary
            
        Returns:
            Dictionary with compliance report data
        """
        report = {
            "document_type": "Compliance Audit Report",
            "organization": self.organization_name,
            "organization_tin": self.organization_tin,
            "report_date": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            "report_version": self.report_version,
            
            "executive_summary": {
                "total_records_scanned": scan_results.get("total_records", 0),
                "overall_risk_level": scan_results.get("overall_risk", "LOW"),
                "total_violations": violation_summary.get("total_violations", 0),
                "audit_status": "PASSED" if scan_results.get("overall_risk") == "low" else "REVIEW REQUIRED"
            },
            
            "risk_breakdown": {
                "critical": violation_summary.get("by_severity", {}).get("critical", 0),
                "high": violation_summary.get("by_severity", {}).get("high", 0),
                "medium": violation_summary.get("by_severity", {}).get("medium", 0)
            },
            
            "violation_categories": violation_summary.get("by_rule", {}),
            
            "detailed_checks": scan_results.get("checks", {}),
            
            "recommendations": {
                "immediate_action": [
                    "Review all CRITICAL severity violations",
                    "Complete vendor verifications for missing TINs",
                    "Escalate budget limit overages for approval"
                ],
                "within_5_days": [
                    "Investigate HIGH severity violations",
                    "Implement corrective controls",
                    "Document remediation actions"
                ],
                "within_30_days": [
                    "Review control effectiveness",
                    "Update compliance procedures",
                    "Provide team training on flagged issues"
                ]
            },
            
            "auditor_notes": "This report is suitable for external audit review.",
            "certification": "Generated by CFO Pulse AI Compliance Engine - Certified Audit Report"
        }
        
        return report
    
    def create_financial_health_report(self, financial_data: Dict,
                                      cash_info: Dict = None) -> Dict:
        """
        Create executive financial health report.
        
        Args:
            financial_data: Dictionary with key financial metrics
            cash_info: Optional dictionary with cash/liquidity info
            
        Returns:
            Dictionary with financial health report data
        """
        if cash_info is None:
            cash_info = {}
        
        # Calculate health score
        health_score = 100
        if financial_data.get("critical_alerts", 0) > 0:
            health_score -= 20
        if financial_data.get("compliance_violations", 0) > 0:
            health_score -= 15
        if cash_info.get("days_until_critical", 30) < 7:
            health_score -= 15
        
        health_status = "Excellent" if health_score >= 80 else "Good" if health_score >= 65 else "Fair" if health_score >= 45 else "Poor"
        
        report = {
            "document_type": "Financial Health Report",
            "organization": self.organization_name,
            "organization_tin": self.organization_tin,
            "report_date": datetime.now().strftime("%Y-%m-%d"),
            "report_version": self.report_version,
            
            "financial_health_score": {
                "score": health_score,
                "max_score": 100,
                "status": health_status
            },
            
            "transaction_metrics": {
                "total_transactions": financial_data.get("total_transactions", 0),
                "total_amount": financial_data.get("total_amount", 0),
                "total_tax": financial_data.get("total_tax", 0),
                "average_transaction": financial_data.get("average_transaction", 0)
            },
            
            "liquidity_position": {
                "cash_balance": cash_info.get("cash_balance", 0),
                "minimum_required": cash_info.get("minimum_required", 0),
                "cash_health": "Healthy" if cash_info.get("cash_balance", 0) > cash_info.get("minimum_required", 0) else "At Risk"
            },
            
            "risk_dashboard": {
                "critical_alerts": financial_data.get("critical_alerts", 0),
                "compliance_violations": financial_data.get("compliance_violations", 0),
                "overall_risk": "Low" if financial_data.get("critical_alerts", 0) == 0 else "Medium" if financial_data.get("critical_alerts", 0) <= 2 else "High"
            },
            
            "action_items": {
                "immediate": [
                    "Address critical alerts" if financial_data.get("critical_alerts", 0) > 0 else "No immediate action needed"
                ],
                "weekly": [
                    "Review compliance violations" if financial_data.get("compliance_violations", 0) > 0 else "Standard monitoring"
                ],
                "monthly": [
                    "Tax compliance review",
                    "Cash flow projection",
                    "Budget variance analysis"
                ]
            },
            
            "certification": "Generated by CFO Pulse AI Analytics Engine"
        }
        
        return report
    
    def create_vendor_reconciliation_report(self, vendors_df: pd.DataFrame) -> Dict:
        """
        Create vendor reconciliation report.
        
        Args:
            vendors_df: DataFrame with vendor information
            
        Returns:
            Dictionary with vendor report data
        """
        if vendors_df is None or vendors_df.empty:
            vendors_df = pd.DataFrame()
        
        report = {
            "document_type": "Vendor Reconciliation Report",
            "organization": self.organization_name,
            "organization_tin": self.organization_tin,
            "report_date": datetime.now().strftime("%Y-%m-%d"),
            "report_version": self.report_version,
            
            "vendor_summary": {
                "total_vendors": len(vendors_df) if not vendors_df.empty else 0,
                "vendors_with_tin": len(vendors_df[vendors_df.get("tin", "").notna()]) if not vendors_df.empty else 0,
                "vendors_without_tin": len(vendors_df[vendors_df.get("tin", "").isna()]) if not vendors_df.empty else 0,
                "unverified_vendors": len(vendors_df[vendors_df.get("verified", False) == False]) if not vendors_df.empty else 0
            },
            
            "action_items": {
                "immediate": [
                    "Obtain TIN for vendors missing tax identification",
                    "Complete vendor verification process"
                ],
                "ongoing": [
                    "Maintain updated vendor master file",
                    "Monthly reconciliation of vendor records"
                ]
            },
            
            "certification": "Generated by CFO Pulse AI Vendor Management System"
        }
        
        return report
    
    def export_report_to_json(self, report: Dict, filename: str = None) -> str:
        """
        Export report to JSON format.
        
        Args:
            report: Report dictionary
            filename: Optional filename (if None, returns JSON string)
            
        Returns:
            JSON string representation of report
        """
        json_str = json.dumps(report, indent=2, default=str)
        
        if filename:
            with open(filename, 'w') as f:
                f.write(json_str)
            return f"Report exported to {filename}"
        
        return json_str
    
    def export_report_summary_text(self, report: Dict) -> str:
        """
        Export report as formatted text summary.
        
        Args:
            report: Report dictionary
            
        Returns:
            Formatted text representation
        """
        output = []
        output.append("=" * 80)
        output.append(f"{report.get('document_type', 'Report').upper()}")
        output.append("=" * 80)
        output.append("")
        output.append(f"Organization: {report.get('organization', 'Unknown')}")
        output.append(f"TIN: {report.get('organization_tin', 'N/A')}")
        output.append(f"Report Date: {report.get('report_date', 'N/A')}")
        output.append("")
        
        # Executive Summary
        if "executive_summary" in report:
            output.append("-" * 80)
            output.append("EXECUTIVE SUMMARY")
            output.append("-" * 80)
            for key, value in report["executive_summary"].items():
                output.append(f"{key.replace('_', ' ').title()}: {value}")
            output.append("")
        
        # Additional sections
        for section_key, section_value in report.items():
            if section_key not in ["document_type", "organization", "organization_tin",
                                   "report_date", "report_version", "executive_summary"]:
                if isinstance(section_value, dict):
                    output.append("-" * 80)
                    output.append(f"{section_key.replace('_', ' ').upper()}")
                    output.append("-" * 80)
                    for sub_key, sub_value in section_value.items():
                        output.append(f"  {sub_key.replace('_', ' ').title()}: {sub_value}")
                    output.append("")
        
        output.append("=" * 80)
        output.append(f"Certification: {report.get('certification', 'N/A')}")
        output.append("=" * 80)
        
        return "\n".join(output)
    
    def get_report_metadata(self, report: Dict) -> Dict:
        """
        Extract metadata from report.
        
        Args:
            report: Report dictionary
            
        Returns:
            Dictionary with report metadata
        """
        return {
            "document_type": report.get("document_type", "Unknown"),
            "organization": report.get("organization", "Unknown"),
            "organization_tin": report.get("organization_tin", "Unknown"),
            "report_date": report.get("report_date", "Unknown"),
            "report_version": report.get("report_version", "1.0")
        }
